--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.567.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/28/2021 11:19:50 PM
-- Server version: 10.4.18
-- Client version: 4.1
--


-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS paupservisvozila;

CREATE DATABASE IF NOT EXISTS paupservisvozila
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Set default database
--
USE paupservisvozila;

--
-- Create table `ovlasti`
--
CREATE TABLE IF NOT EXISTS ovlasti (
  sifra varchar(5) NOT NULL,
  naziv varchar(255) NOT NULL,
  PRIMARY KEY (sifra)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `korisnici`
--
CREATE TABLE IF NOT EXISTS korisnici (
  korisnicko_ime varchar(30) NOT NULL,
  Ime varchar(45) NOT NULL,
  Prezime varchar(45) DEFAULT NULL,
  MobilniBroj int(10) DEFAULT NULL,
  Email varchar(100) NOT NULL,
  Lozinka varchar(255) NOT NULL,
  ovlast varchar(5) DEFAULT NULL,
  PRIMARY KEY (korisnicko_ime)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE korisnici
ADD CONSTRAINT FK_korisnici_ovlasti FOREIGN KEY (ovlast)
REFERENCES ovlasti (sifra) ON DELETE NO ACTION;

--
-- Create table `marke_automobili`
--
CREATE TABLE IF NOT EXISTS marke_automobili (
  id int(2) DEFAULT NULL,
  Marke varchar(35) NOT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `UK_marke_automobili_id` on table `marke_automobili`
--
ALTER TABLE marke_automobili
ADD UNIQUE INDEX UK_marke_automobili_id (id);

--
-- Create table `automobili`
--
CREATE TABLE IF NOT EXISTS automobili (
  VIN varchar(17) NOT NULL,
  KorisnikID varchar(30) NOT NULL,
  Proizvodac int(2) DEFAULT NULL,
  Model varchar(15) NOT NULL,
  Registracija varchar(11) NOT NULL,
  PRIMARY KEY (VIN)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE automobili
ADD CONSTRAINT FK_automobili_Proizvodac FOREIGN KEY (Proizvodac)
REFERENCES marke_automobili (id) ON DELETE NO ACTION ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE automobili
ADD CONSTRAINT FK_automobili_korisnikID FOREIGN KEY (KorisnikID)
REFERENCES korisnici (korisnicko_ime) ON DELETE NO ACTION ON UPDATE CASCADE;

--
-- Create table `status`
--
CREATE TABLE IF NOT EXISTS status (
  id int(2) NOT NULL,
  Status varchar(35) NOT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `id` on table `status`
--
ALTER TABLE status
ADD UNIQUE INDEX id (id);

--
-- Create table `servisi`
--
CREATE TABLE IF NOT EXISTS servisi (
  ID_Servisa int(2) NOT NULL AUTO_INCREMENT,
  autoID varchar(17) NOT NULL,
  Datum_kreiranja_zahtjeva date NOT NULL,
  Datum_pocetka_servisa date DEFAULT NULL,
  Datum_zavrsetka_servisa date DEFAULT NULL,
  Napomena_vlasnika varchar(255) DEFAULT NULL,
  Napomena_servisera varchar(255) DEFAULT NULL,
  Kilometraza int(6) DEFAULT NULL,
  Serviser varchar(55) DEFAULT NULL,
  Status int(2) NOT NULL,
  PRIMARY KEY (ID_Servisa)
)
ENGINE = INNODB,
AUTO_INCREMENT = 25,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE servisi
ADD CONSTRAINT FK_autoID_VIN FOREIGN KEY (autoID)
REFERENCES automobili (VIN) ON DELETE NO ACTION ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE servisi
ADD CONSTRAINT FK_servisi_Status FOREIGN KEY (Status)
REFERENCES status (id) ON DELETE NO ACTION ON UPDATE CASCADE;

--
-- Create table `racun`
--
CREATE TABLE IF NOT EXISTS racun (
  id int(5) NOT NULL AUTO_INCREMENT,
  servis int(2) NOT NULL,
  Datum date DEFAULT NULL,
  Izdaje_osoba varchar(50) NOT NULL,
  Cijena int(6) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE racun
ADD CONSTRAINT FK_servis_IDServisa FOREIGN KEY (servis)
REFERENCES servisi (ID_Servisa) ON DELETE NO ACTION ON UPDATE CASCADE;

--
-- Create table `artikli`
--
CREATE TABLE IF NOT EXISTS artikli (
  id int(11) NOT NULL AUTO_INCREMENT,
  naziv varchar(35) NOT NULL,
  jedinica_mjere varchar(5) NOT NULL,
  cijena int(5) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `racun_stavke`
--
CREATE TABLE IF NOT EXISTS racun_stavke (
  id int(5) NOT NULL,
  id_racuna int(5) NOT NULL,
  redni_broj_stavke int(5) NOT NULL,
  sifra_artikla int(11) NOT NULL,
  kolicina int(11) NOT NULL,
  iznos int(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `IDX_racun_stavke_id_racuna` on table `racun_stavke`
--
ALTER TABLE racun_stavke
ADD INDEX IDX_racun_stavke_id_racuna (id_racuna);

--
-- Create index `UK_racun_stavke_id_racuna` on table `racun_stavke`
--
ALTER TABLE racun_stavke
ADD INDEX UK_racun_stavke_id_racuna (id_racuna);

--
-- Create index `UK_racun_stavke_sifra_artikla` on table `racun_stavke`
--
ALTER TABLE racun_stavke
ADD UNIQUE INDEX UK_racun_stavke_sifra_artikla (sifra_artikla);

--
-- Create foreign key
--
ALTER TABLE racun_stavke
ADD CONSTRAINT FK_id_racuna__racun_id FOREIGN KEY (id_racuna)
REFERENCES racun (id) ON DELETE NO ACTION ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE racun_stavke
ADD CONSTRAINT FK_sifra_artikla__id_artikla FOREIGN KEY (sifra_artikla)
REFERENCES artikli (id) ON DELETE NO ACTION ON UPDATE CASCADE;

-- 
-- Dumping data for table ovlasti
--
INSERT INTO ovlasti VALUES
('AD', 'Administrator'),
('US', 'Korisnik');

-- 
-- Dumping data for table marke_automobili
--
INSERT INTO marke_automobili VALUES
(1, 'Audi'),
(2, 'BMW'),
(3, 'Mercedes'),
(4, 'Mazda'),
(5, 'Opel'),
(6, 'Peugeot');

-- 
-- Dumping data for table korisnici
--
INSERT INTO korisnici VALUES
('per122', 'Pero', 'Perić', 952152345, 'peroperic@gmail.com', 'jUPY60RIRBTWGhhlm0Q/v+UjmVENpGidU1K9ljHGxRs=', 'AD');

-- 
-- Dumping data for table status
--
INSERT INTO status VALUES
(1, 'Zahtjev kreiran'),
(2, 'Vozilo servisirano'),
(3, 'Zahtjev storniran');

-- 
-- Dumping data for table automobili
--
INSERT INTO automobili VALUES
('1G1AP14PX67607352', 'per122', 1, 'asdfasdf', 'asdf12'),
('1HGCG5644WA047116', 'per122', 1, 'M3', 'VŽ-356-CS'),
('1HTLKTVR4HH508441', 'per122', 2, 'M3', 'VŽ-356-CS');

-- 
-- Dumping data for table servisi
--
-- Table paupservisvozila.servisi does not contain any data (it is empty)

-- 
-- Dumping data for table racun
--
-- Table paupservisvozila.racun does not contain any data (it is empty)

-- 
-- Dumping data for table artikli
--
-- Table paupservisvozila.artikli does not contain any data (it is empty)

-- 
-- Dumping data for table racun_stavke
--
-- Table paupservisvozila.racun_stavke does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;